# Generated by Django 2.2.2 on 2019-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theSortingHat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hat',
            field=models.CharField(blank=True, choices=[('Griffindor', 'Griffindor'), ('Hufflepuff', 'Hufflepuff'), ('Ravenclaw', 'Ravenclaw'), ('Slitherin', 'Slitherin')], max_length=10, null=True),
        ),
    ]
